<?php

namespace Database\Seeders;

use App\Models\SectorType;
use Illuminate\Database\Seeder;

class SectorTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            // 1. الضيافة والسياحة
            ['id' => 'travel_agency',       'sector_id' => 'hospitality_tourism',    'label' => 'وكالة سياحة',             'label_en' => 'Travel Agency',           'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'reminder'],               'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'hotel',               'sector_id' => 'hospitality_tourism',    'label' => 'فندق',                    'label_en' => 'Hotel',                   'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'reminder', 'rating'],     'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'chalets_resorts',     'sector_id' => 'hospitality_tourism',    'label' => 'شاليهات واستراحات',       'label_en' => 'Chalets & Resorts',       'default_patterns' => ['rental', 'catalog_browse'],                         'default_layers' => ['payment', 'reminder', 'rating'],     'sector_rules' => 'rental',   'sort_order' => 3],
            ['id' => 'spa',                 'sector_id' => 'hospitality_tourism',    'label' => 'منتجع صحي',               'label_en' => 'Spa',                     'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'reminder', 'rating'],     'sector_rules' => null,       'sort_order' => 4],
            ['id' => 'trips_company',       'sector_id' => 'hospitality_tourism',    'label' => 'شركة رحلات برية',         'label_en' => 'Trips Company',           'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'reminder'],               'sector_rules' => null,       'sort_order' => 5],

            // 2. الصحة والعناية الشخصية
            ['id' => 'salon_women',         'sector_id' => 'health_beauty',          'label' => 'صالون نسائي',              'label_en' => "Women's Salon",           'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'rating'],                'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'barber_men',          'sector_id' => 'health_beauty',          'label' => 'حلاق رجالي',              'label_en' => "Men's Barber",            'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'rating'],                'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'clinic',              'sector_id' => 'health_beauty',          'label' => 'عيادة',                    'label_en' => 'Clinic',                  'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'rating', 'documents'],   'sector_rules' => 'medical',  'sort_order' => 3],
            ['id' => 'medical_center',      'sector_id' => 'health_beauty',          'label' => 'مركز طبي',                 'label_en' => 'Medical Center',          'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'rating', 'documents'],   'sector_rules' => 'medical',  'sort_order' => 4],
            ['id' => 'dental_center',       'sector_id' => 'health_beauty',          'label' => 'مركز أسنان',               'label_en' => 'Dental Center',           'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'rating'],                'sector_rules' => 'medical',  'sort_order' => 5],
            ['id' => 'lab',                 'sector_id' => 'health_beauty',          'label' => 'مختبر تحاليل',             'label_en' => 'Lab',                     'default_patterns' => ['booking', 'catalog_browse', 'status_tracking'],     'default_layers' => ['reminder'],                          'sector_rules' => 'medical',  'sort_order' => 6],

            // 3. البيع بالتجزئة
            ['id' => 'grocery',             'sector_id' => 'retail',                 'label' => 'بقالة',                    'label_en' => 'Grocery',                 'default_patterns' => ['product_order', 'catalog_browse'],                  'default_layers' => ['delivery', 'payment'],               'sector_rules' => 'food',     'sort_order' => 1],
            ['id' => 'product_store',       'sector_id' => 'retail',                 'label' => 'متجر منتجات',              'label_en' => 'Product Store',           'default_patterns' => ['product_order', 'catalog_browse', 'recommend'],     'default_layers' => ['delivery', 'payment', 'warranty'],   'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'car_showroom',        'sector_id' => 'retail',                 'label' => 'معرض سيارات',              'label_en' => 'Car Showroom',            'default_patterns' => ['catalog_browse', 'recommend', 'client_qualification'], 'default_layers' => ['followup'],                       'sector_rules' => null,       'sort_order' => 3],
            ['id' => 'electronics_store',   'sector_id' => 'retail',                 'label' => 'معرض أجهزة',               'label_en' => 'Electronics Store',       'default_patterns' => ['product_order', 'catalog_browse', 'recommend'],     'default_layers' => ['delivery', 'payment', 'warranty'],   'sector_rules' => null,       'sort_order' => 4],
            ['id' => 'furniture_store',     'sector_id' => 'retail',                 'label' => 'محل مفروشات',              'label_en' => 'Furniture Store',         'default_patterns' => ['product_order', 'catalog_browse', 'recommend'],     'default_layers' => ['delivery', 'payment', 'warranty'],   'sector_rules' => null,       'sort_order' => 5],
            ['id' => 'phone_store',         'sector_id' => 'retail',                 'label' => 'محل جوالات',               'label_en' => 'Phone Store',             'default_patterns' => ['product_order', 'catalog_browse', 'recommend'],     'default_layers' => ['delivery', 'payment', 'warranty'],   'sector_rules' => null,       'sort_order' => 6],
            ['id' => 'perfume_store',       'sector_id' => 'retail',                 'label' => 'محل عطور',                 'label_en' => 'Perfume Store',           'default_patterns' => ['product_order', 'catalog_browse', 'recommend'],     'default_layers' => ['delivery', 'payment'],               'sector_rules' => null,       'sort_order' => 7],

            // 4. الخدمات المهنية والاستشارية
            ['id' => 'engineering_office',  'sector_id' => 'professional_services',  'label' => 'مكتب هندسي',               'label_en' => 'Engineering Office',      'default_patterns' => ['client_qualification', 'booking'],                  'default_layers' => ['documents', 'followup'],             'sector_rules' => 'legal',    'sort_order' => 1],
            ['id' => 'law_firm',            'sector_id' => 'professional_services',  'label' => 'مكتب محاماة',              'label_en' => 'Law Firm',                'default_patterns' => ['client_qualification', 'booking'],                  'default_layers' => ['documents', 'followup'],             'sector_rules' => 'legal',    'sort_order' => 2],
            ['id' => 'insurance_company',   'sector_id' => 'professional_services',  'label' => 'شركة تأمين',               'label_en' => 'Insurance Company',       'default_patterns' => ['client_qualification', 'catalog_browse'],           'default_layers' => ['documents', 'followup'],             'sector_rules' => 'financial','sort_order' => 3],
            ['id' => 'accounting_office',   'sector_id' => 'professional_services',  'label' => 'مكتب محاسبة',              'label_en' => 'Accounting Office',       'default_patterns' => ['client_qualification', 'booking'],                  'default_layers' => ['documents', 'followup'],             'sector_rules' => 'financial','sort_order' => 4],
            ['id' => 'financial_advisor',   'sector_id' => 'professional_services',  'label' => 'مستشار مالي',              'label_en' => 'Financial Advisor',       'default_patterns' => ['client_qualification', 'booking'],                  'default_layers' => ['documents', 'followup'],             'sector_rules' => 'financial','sort_order' => 5],
            ['id' => 'translation_office',  'sector_id' => 'professional_services',  'label' => 'مكتب ترجمة',               'label_en' => 'Translation Office',      'default_patterns' => ['custom_quote', 'status_tracking'],                 'default_layers' => ['payment', 'documents'],              'sector_rules' => null,       'sort_order' => 6],

            // 5. المقاولات والصيانة والحرف
            ['id' => 'contracting_company', 'sector_id' => 'contracting_maintenance','label' => 'شركة مقاولات',             'label_en' => 'Contracting Company',     'default_patterns' => ['service_request', 'custom_quote'],                 'default_layers' => ['documents', 'followup'],             'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'plumbing_electrical', 'sector_id' => 'contracting_maintenance','label' => 'سباكة وكهرباء',            'label_en' => 'Plumbing & Electrical',   'default_patterns' => ['service_request'],                                 'default_layers' => ['followup', 'rating'],                'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'elevator_company',    'sector_id' => 'contracting_maintenance','label' => 'شركة مصاعد',               'label_en' => 'Elevator Company',        'default_patterns' => ['service_request', 'custom_quote'],                 'default_layers' => ['warranty', 'followup'],              'sector_rules' => null,       'sort_order' => 3],
            ['id' => 'carpentry_workshop',  'sector_id' => 'contracting_maintenance','label' => 'ورشة نجارة',               'label_en' => 'Carpentry Workshop',      'default_patterns' => ['custom_quote', 'service_request'],                 'default_layers' => ['followup'],                          'sector_rules' => null,       'sort_order' => 4],
            ['id' => 'upholstery_shop',     'sector_id' => 'contracting_maintenance','label' => 'محل تنجيد',                'label_en' => 'Upholstery Shop',         'default_patterns' => ['custom_quote', 'service_request'],                 'default_layers' => ['followup'],                          'sector_rules' => null,       'sort_order' => 5],
            ['id' => 'ac_company',          'sector_id' => 'contracting_maintenance','label' => 'شركة تكييف',               'label_en' => 'AC Company',              'default_patterns' => ['service_request'],                                 'default_layers' => ['warranty', 'followup', 'rating'],    'sector_rules' => null,       'sort_order' => 6],
            ['id' => 'cleaning_company',    'sector_id' => 'contracting_maintenance','label' => 'شركة تنظيف',               'label_en' => 'Cleaning Company',        'default_patterns' => ['service_request', 'booking'],                      'default_layers' => ['followup', 'rating'],                'sector_rules' => null,       'sort_order' => 7],
            ['id' => 'blacksmith',          'sector_id' => 'contracting_maintenance','label' => 'حداد',                     'label_en' => 'Blacksmith',              'default_patterns' => ['custom_quote', 'service_request'],                 'default_layers' => ['followup'],                          'sector_rules' => null,       'sort_order' => 8],

            // 6. الخدمات اللوجستية
            ['id' => 'shipping_company',    'sector_id' => 'logistics',              'label' => 'شركة شحن',                 'label_en' => 'Shipping Company',        'default_patterns' => ['status_tracking', 'custom_quote'],                 'default_layers' => ['payment'],                           'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'moving_company',      'sector_id' => 'logistics',              'label' => 'شركة نقل أثاث',            'label_en' => 'Moving Company',          'default_patterns' => ['service_request', 'custom_quote'],                 'default_layers' => ['payment', 'rating'],                 'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'car_rental',          'sector_id' => 'logistics',              'label' => 'شركة تأجير سيارات',        'label_en' => 'Car Rental',              'default_patterns' => ['rental', 'catalog_browse'],                        'default_layers' => ['payment'],                           'sector_rules' => 'rental',   'sort_order' => 3],
            ['id' => 'equipment_rental',    'sector_id' => 'logistics',              'label' => 'شركة تأجير معدات',         'label_en' => 'Equipment Rental',        'default_patterns' => ['rental', 'catalog_browse'],                        'default_layers' => ['payment'],                           'sector_rules' => 'rental',   'sort_order' => 4],

            // 7. التعليم والتدريب
            ['id' => 'training_center',     'sector_id' => 'education_training',     'label' => 'مركز تدريب',               'label_en' => 'Training Center',         'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'reminder', 'rating'],     'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'language_institute',  'sector_id' => 'education_training',     'label' => 'معهد لغات',                'label_en' => 'Language Institute',      'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'reminder', 'subscription'], 'sector_rules' => null,    'sort_order' => 2],
            ['id' => 'nursery',             'sector_id' => 'education_training',     'label' => 'حضانة أطفال',              'label_en' => 'Nursery',                 'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['subscription', 'reminder'],          'sector_rules' => 'children', 'sort_order' => 3],
            ['id' => 'private_school',      'sector_id' => 'education_training',     'label' => 'مدرسة أهلية',              'label_en' => 'Private School',          'default_patterns' => ['client_qualification', 'booking'],                 'default_layers' => ['subscription', 'documents'],         'sector_rules' => 'children', 'sort_order' => 4],
            ['id' => 'online_academy',      'sector_id' => 'education_training',     'label' => 'أكاديمية أونلاين',          'label_en' => 'Online Academy',          'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'subscription'],           'sector_rules' => null,       'sort_order' => 5],

            // 8. خدمات المناسبات
            ['id' => 'event_photography',   'sector_id' => 'events',                 'label' => 'تصوير مناسبات',            'label_en' => 'Event Photography',       'default_patterns' => ['booking', 'catalog_browse', 'custom_quote'],       'default_layers' => ['payment', 'followup'],               'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'event_planning',      'sector_id' => 'events',                 'label' => 'تنظيم حفلات',              'label_en' => 'Event Planning',          'default_patterns' => ['booking', 'custom_quote'],                         'default_layers' => ['payment', 'followup'],               'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'furniture_rental',    'sector_id' => 'events',                 'label' => 'تأجير كراسي وطاولات',      'label_en' => 'Furniture Rental',        'default_patterns' => ['rental', 'catalog_browse'],                        'default_layers' => ['payment', 'delivery'],               'sector_rules' => 'rental',   'sort_order' => 3],
            ['id' => 'flowers_decor',       'sector_id' => 'events',                 'label' => 'كوش وتنسيق زهور',          'label_en' => 'Flowers & Decor',         'default_patterns' => ['booking', 'custom_quote', 'catalog_browse'],       'default_layers' => ['payment', 'followup'],               'sector_rules' => null,       'sort_order' => 4],

            // 9. الوساطة والمنصات
            ['id' => 'real_estate_broker',  'sector_id' => 'brokerage_platforms',    'label' => 'مكتب وساطة عقار',          'label_en' => 'Real Estate Broker',      'default_patterns' => ['catalog_browse', 'recommend', 'client_qualification'], 'default_layers' => ['followup'],                       'sector_rules' => 'real_estate', 'sort_order' => 1],
            ['id' => 'services_marketplace','sector_id' => 'brokerage_platforms',    'label' => 'متجر خدمات',               'label_en' => 'Services Marketplace',    'default_patterns' => ['catalog_browse', 'recommend'],                     'default_layers' => ['payment', 'rating'],                 'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'freelancer_platform', 'sector_id' => 'brokerage_platforms',    'label' => 'منصة فريلانسرز',           'label_en' => 'Freelancer Platform',     'default_patterns' => ['catalog_browse', 'recommend', 'client_qualification'], 'default_layers' => ['payment', 'rating'],              'sector_rules' => null,       'sort_order' => 3],
            ['id' => 'domestic_workers_app','sector_id' => 'brokerage_platforms',    'label' => 'تطبيق عمالة منزلية',       'label_en' => 'Domestic Workers App',    'default_patterns' => ['catalog_browse', 'recommend', 'booking'],          'default_layers' => ['payment', 'documents'],              'sector_rules' => null,       'sort_order' => 4],

            // 10. التسويق والإعلام
            ['id' => 'ad_agency',           'sector_id' => 'marketing_media',        'label' => 'وكالة دعاية',              'label_en' => 'Ad Agency',               'default_patterns' => ['client_qualification', 'custom_quote'],            'default_layers' => ['documents', 'followup'],             'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'digital_marketing',   'sector_id' => 'marketing_media',        'label' => 'شركة تسويق رقمي',          'label_en' => 'Digital Marketing',       'default_patterns' => ['client_qualification', 'custom_quote'],            'default_layers' => ['documents', 'followup', 'subscription'], 'sector_rules' => null, 'sort_order' => 2],
            ['id' => 'video_production',    'sector_id' => 'marketing_media',        'label' => 'شركة إنتاج فيديو',         'label_en' => 'Video Production',        'default_patterns' => ['client_qualification', 'custom_quote'],            'default_layers' => ['followup'],                          'sector_rules' => null,       'sort_order' => 3],
            ['id' => 'print_shop',          'sector_id' => 'marketing_media',        'label' => 'مطبعة',                    'label_en' => 'Print Shop',              'default_patterns' => ['product_order', 'custom_quote'],                   'default_layers' => ['delivery', 'payment'],               'sector_rules' => null,       'sort_order' => 4],

            // 11. التقنية وتكنولوجيا المعلومات
            ['id' => 'software_company',    'sector_id' => 'technology',             'label' => 'شركة برمجيات',             'label_en' => 'Software Company',        'default_patterns' => ['client_qualification', 'custom_quote'],            'default_layers' => ['documents', 'followup', 'subscription'], 'sector_rules' => null, 'sort_order' => 1],
            ['id' => 'hosting_support',     'sector_id' => 'technology',             'label' => 'شركة استضافة ودعم فني',    'label_en' => 'Hosting & Support',       'default_patterns' => ['client_qualification', 'status_tracking'],         'default_layers' => ['subscription'],                      'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'cybersecurity',       'sector_id' => 'technology',             'label' => 'شركة أمن سيبراني',         'label_en' => 'Cybersecurity',           'default_patterns' => ['client_qualification', 'custom_quote'],            'default_layers' => ['documents', 'subscription'],         'sector_rules' => null,       'sort_order' => 3],
            ['id' => 'surveillance_systems','sector_id' => 'technology',             'label' => 'شركة أنظمة مراقبة',        'label_en' => 'Surveillance Systems',    'default_patterns' => ['service_request', 'custom_quote'],                 'default_layers' => ['warranty', 'followup'],              'sector_rules' => null,       'sort_order' => 4],

            // 12. الخدمات المالية
            ['id' => 'exchange_office',     'sector_id' => 'financial_services',     'label' => 'مكتب صرافة',               'label_en' => 'Exchange Office',         'default_patterns' => ['catalog_browse'],                                  'default_layers' => [],                                    'sector_rules' => 'financial','sort_order' => 1],
            ['id' => 'finance_company',     'sector_id' => 'financial_services',     'label' => 'شركة تمويل',               'label_en' => 'Finance Company',         'default_patterns' => ['client_qualification'],                            'default_layers' => ['documents'],                         'sector_rules' => 'financial','sort_order' => 2],
            ['id' => 'collection_office',   'sector_id' => 'financial_services',     'label' => 'مكتب تحصيل',               'label_en' => 'Collection Office',       'default_patterns' => ['status_tracking'],                                 'default_layers' => ['documents'],                         'sector_rules' => 'financial','sort_order' => 3],
            ['id' => 'tax_zakat_office',    'sector_id' => 'financial_services',     'label' => 'مكتب زكاة وضريبة',         'label_en' => 'Tax & Zakat Office',      'default_patterns' => ['client_qualification', 'status_tracking'],         'default_layers' => ['documents'],                         'sector_rules' => 'financial','sort_order' => 4],

            // 13. العقارات والتطوير
            ['id' => 'real_estate_dev',     'sector_id' => 'real_estate',            'label' => 'شركة تطوير عقاري',         'label_en' => 'Real Estate Developer',   'default_patterns' => ['catalog_browse', 'recommend', 'client_qualification'], 'default_layers' => ['followup'],                       'sector_rules' => 'real_estate', 'sort_order' => 1],
            ['id' => 'property_management', 'sector_id' => 'real_estate',            'label' => 'شركة إدارة أملاك',         'label_en' => 'Property Management',     'default_patterns' => ['service_request', 'status_tracking'],              'default_layers' => ['followup'],                          'sector_rules' => 'real_estate', 'sort_order' => 2],
            ['id' => 'valuation_office',    'sector_id' => 'real_estate',            'label' => 'مكتب تثمين',               'label_en' => 'Valuation Office',        'default_patterns' => ['client_qualification', 'custom_quote'],            'default_layers' => ['documents'],                         'sector_rules' => 'real_estate', 'sort_order' => 3],

            // 14. الزراعة والغذاء
            ['id' => 'farm',                'sector_id' => 'agriculture_food',       'label' => 'مزرعة',                    'label_en' => 'Farm',                    'default_patterns' => ['product_order', 'catalog_browse'],                  'default_layers' => ['delivery', 'payment'],               'sector_rules' => 'food',     'sort_order' => 1],
            ['id' => 'flowers_nursery',     'sector_id' => 'agriculture_food',       'label' => 'محل ورد ومشاتل',           'label_en' => 'Flowers & Nursery',       'default_patterns' => ['product_order', 'catalog_browse'],                  'default_layers' => ['delivery', 'payment'],               'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'honey_dates',         'sector_id' => 'agriculture_food',       'label' => 'متجر عسل وتمور',           'label_en' => 'Honey & Dates',           'default_patterns' => ['product_order', 'catalog_browse'],                  'default_layers' => ['delivery', 'payment'],               'sector_rules' => 'food',     'sort_order' => 3],
            ['id' => 'meat_factory',        'sector_id' => 'agriculture_food',       'label' => 'معمل لحوم',                'label_en' => 'Meat Factory',            'default_patterns' => ['product_order', 'catalog_browse'],                  'default_layers' => ['delivery', 'payment'],               'sector_rules' => 'food',     'sort_order' => 4],

            // 15. الصناعة والتصنيع
            ['id' => 'small_factory',       'sector_id' => 'manufacturing',          'label' => 'مصنع صغير',                'label_en' => 'Small Factory',           'default_patterns' => ['custom_quote', 'product_order'],                   'default_layers' => ['payment', 'delivery'],               'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'tailor_workshop',     'sector_id' => 'manufacturing',          'label' => 'مشغل خياطة',               'label_en' => 'Tailor Workshop',         'default_patterns' => ['custom_quote', 'booking'],                         'default_layers' => ['payment', 'followup'],               'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'bakery_sweets',       'sector_id' => 'manufacturing',          'label' => 'معمل حلويات ومخبوزات',     'label_en' => 'Bakery & Sweets',         'default_patterns' => ['product_order', 'custom_quote', 'catalog_browse'], 'default_layers' => ['delivery', 'payment'],               'sector_rules' => 'food',     'sort_order' => 3],

            // 16. خدمات الحيوانات
            ['id' => 'vet_clinic',          'sector_id' => 'animal_services',        'label' => 'عيادة بيطرية',             'label_en' => 'Vet Clinic',              'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'rating'],                'sector_rules' => 'animals',  'sort_order' => 1],
            ['id' => 'pet_store',           'sector_id' => 'animal_services',        'label' => 'متجر حيوانات أليفة',       'label_en' => 'Pet Store',               'default_patterns' => ['product_order', 'catalog_browse'],                  'default_layers' => ['delivery', 'payment'],               'sector_rules' => 'animals',  'sort_order' => 2],
            ['id' => 'dog_training',        'sector_id' => 'animal_services',        'label' => 'مركز تدريب كلاب',          'label_en' => 'Dog Training',            'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['reminder', 'subscription'],          'sector_rules' => 'animals',  'sort_order' => 3],

            // 17. الخدمات الشخصية والمنزلية
            ['id' => 'laundry',             'sector_id' => 'personal_home_services', 'label' => 'مصبغة',                    'label_en' => 'Laundry',                 'default_patterns' => ['service_request', 'status_tracking'],              'default_layers' => ['delivery', 'payment', 'rating'],     'sector_rules' => null,       'sort_order' => 1],
            ['id' => 'home_cleaning',       'sector_id' => 'personal_home_services', 'label' => 'شركة تنظيف منازل',         'label_en' => 'Home Cleaning',           'default_patterns' => ['service_request', 'booking'],                      'default_layers' => ['payment', 'rating'],                 'sector_rules' => null,       'sort_order' => 2],
            ['id' => 'private_chef',        'sector_id' => 'personal_home_services', 'label' => 'خدمة شيف خاص',             'label_en' => 'Private Chef',            'default_patterns' => ['booking', 'catalog_browse'],                        'default_layers' => ['payment', 'rating'],                 'sector_rules' => 'food',     'sort_order' => 3],
            ['id' => 'furniture_moving',    'sector_id' => 'personal_home_services', 'label' => 'شركة نقل أثاث',            'label_en' => 'Furniture Moving',         'default_patterns' => ['service_request', 'custom_quote'],                 'default_layers' => ['payment', 'rating'],                 'sector_rules' => null,       'sort_order' => 4],

            // 18. الخدمات الحكومية والتنظيمية
            ['id' => 'recruitment_office',  'sector_id' => 'government_services',    'label' => 'مكتب استقدام',              'label_en' => 'Recruitment Office',      'default_patterns' => ['client_qualification', 'status_tracking'],         'default_layers' => ['documents', 'payment'],              'sector_rules' => 'government','sort_order' => 1],
            ['id' => 'gov_services_office', 'sector_id' => 'government_services',    'label' => 'مكتب تعقيب وخدمات عامة',   'label_en' => 'Gov Services Office',     'default_patterns' => ['service_request', 'status_tracking'],              'default_layers' => ['documents'],                         'sector_rules' => 'government','sort_order' => 2],
            ['id' => 'e_services_office',   'sector_id' => 'government_services',    'label' => 'مكتب خدمات إلكترونية',     'label_en' => 'E-Services Office',       'default_patterns' => ['service_request', 'status_tracking'],              'default_layers' => ['documents', 'payment'],              'sector_rules' => 'government','sort_order' => 3],
            ['id' => 'employment_company',  'sector_id' => 'government_services',    'label' => 'شركة توظيف',               'label_en' => 'Employment Company',      'default_patterns' => ['client_qualification', 'catalog_browse'],           'default_layers' => ['documents', 'followup'],             'sector_rules' => null,       'sort_order' => 4],
        ];

        foreach ($types as $type) {
            SectorType::create($type);
        }
    }
}
